fix: coveralls only on public repositories (#21)

diff --git a/.github/workflows/apps-build.yml b/.github/workflows/apps-build.yml
--- a/.github/workflows/apps-build.yml
+++ b/.github/workflows/apps-build.yml
@@ -35,8 +35,36 @@ jobs:
         run: yarn build
       - name: test
         run: yarn test --coverage
+      - name: hide coveralls if repo is private
+        id: repo-visibility
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/${{ github.repository }})
+
+          # Validate and parse JSON response
+          if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
+              IS_PRIVATE=$(echo "$RESPONSE" | jq -r '.private')
+          else
+              echo "Error: API response is not valid JSON or malformed."
+              exit 1
+          fi
+
+          echo $IS_PRIVATE
+          # Set environment variable for coveralls
+          if [ "$IS_PRIVATE" = 'true' ]; then
+              echo "continue-coveralls=false" >> $GITHUB_OUTPUT
+          else
+              echo "continue-coveralls=true" >> $GITHUB_OUTPUT
+          fi
+
       - name: report coverage
+        if: steps.repo-visibility.outputs.continue-coveralls == 'true'
         uses: coverallsapp/github-action@master
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}          
+          github-token: ${{ secrets.GITHUB_TOKEN }}
           path-to-lcov: ./coverage/lcov.info
+
+          
diff --git a/.github/workflows/apps-with-db-build.yml b/.github/workflows/apps-with-db-build.yml
--- a/.github/workflows/apps-with-db-build.yml
+++ b/.github/workflows/apps-with-db-build.yml
@@ -51,12 +51,39 @@ jobs:
         run: yarn test
         env:
           PG_COMPONENT_PSQL_CONNECTION_STRING: postgres://postgres:pass1234@localhost/db
+      - name: hide coveralls if repo is private
+        id: repo-visibility
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/${{ github.repository }})
+
+          # Validate and parse JSON response
+          if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
+              IS_PRIVATE=$(echo "$RESPONSE" | jq -r '.private')
+          else
+              echo "Error: API response is not valid JSON or malformed."
+              exit 1
+          fi
+
+          echo $IS_PRIVATE
+          # Set environment variable for coveralls
+          if [ "$IS_PRIVATE" = 'true' ]; then
+              echo "continue-coveralls=false" >> $GITHUB_OUTPUT
+          else
+              echo "continue-coveralls=true" >> $GITHUB_OUTPUT
+          fi
+  
       - name: find coverage files in any workspace or root
+        if: steps.repo-visibility.outputs.continue-coveralls == 'true'
         run: |
           coverage_files=$(find ./ -type f -name 'lcov.info' -not -path '*/node_modules/*')
-          echo "COVERAGE_FILES=$(echo $coverage_files | tr '\n' ' ')" >> $GITHUB_ENV
+          echo "COVERAGE_FILES=$(echo $coverage_files | tr '\n' ' ')" >> $GITHUB_OUTPUT
 
       - name: report coverage to coveralls
+        if: steps.repo-visibility.outputs.continue-coveralls == 'true'
         uses: coverallsapp/github-action@v2
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
